#!/bin/bash

echo ""
echo "👤 CREATING ADMIN USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📧 Email: travunited3@gmail.com"
echo "🔑 Password: Marigudi@9"
echo "👑 Role: Admin"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 METHOD 1: Via Supabase SQL Editor (RECOMMENDED)"
echo ""
echo "   1. Open: https://supabase.com/dashboard/project/esbzzprfghkcigvyuiw/sql"
echo "   2. Open file: database/create-admin-user.sql in VS Code"
echo "   3. Select All (Cmd+A)"
echo "   4. Copy (Cmd+C)"
echo "   5. Paste in SQL Editor (Cmd+V)"
echo "   6. Click 'Run'"
echo "   7. See: '✅ Admin user created: travunited3@gmail.com'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 METHOD 2: Via Supabase Dashboard (EASIER)"
echo ""
echo "   1. Go to: https://supabase.com/dashboard/project/esbzzprfghkcigvyuiw/auth/users"
echo "   2. Click 'Add User'"
echo "   3. Email: travunited3@gmail.com"
echo "   4. Password: Marigudi@9"
echo "   5. Auto Confirm User: YES"
echo "   6. Click 'Create User'"
echo ""
echo "   Then set as admin:"
echo "   7. Click on the created user"
echo "   8. Scroll to 'User Metadata'"
echo "   9. Add: {\"role\": \"admin\", \"is_admin\": true}"
echo "   10. Click 'Save'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After creation, you can login at:"
echo "   http://localhost:3000/login"
echo ""
echo "   Email: travunited3@gmail.com"
echo "   Password: Marigudi@9"
echo ""
echo "🎯 Opening Auth Dashboard..."
echo ""

# Open Supabase Auth Users page
open "https://supabase.com/dashboard/project/esbzzprfghkcigvyuiw/auth/users"

sleep 2

echo "✅ Supabase Auth Dashboard opened!"
echo ""
echo "📝 Click 'Add User' and use the credentials above."
echo ""

