#!/bin/bash

# Open Supabase SQL Editor with instructions
echo ""
echo "🚀 TRAVUNITED - AUTOMATED DATABASE SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Supabase CLI Installed: v2.54.11"
echo "✅ Migrations Ready: 5 files"
echo "✅ Service Key: Configured"
echo ""
echo "⚠️  IMPORTANT:"
echo "   Supabase API doesn't support complex DDL via REST/CLI"
echo "   (Functions, Triggers, RLS Policies require SQL Editor)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 OPENING SUPABASE SQL EDITOR..."
echo ""

# Open Supabase SQL Editor in browser
open "https://supabase.com/dashboard/project/esbzzprfghkcigvyuiw/sql"

sleep 2

echo "✅ SQL Editor opened in browser!"
echo ""
echo "📋 NOW DO THIS (5 MINUTES):"
echo ""
echo "   In VS Code (this editor):"
echo "   ========================="
echo ""
echo "   1. Open: database/schema.sql"
echo "      → Select All (Cmd+A)"
echo "      → Copy (Cmd+C)"
echo "      → Go to SQL Editor browser tab"
echo "      → Click 'New Query'"
echo "      → Paste (Cmd+V)"
echo "      → Click 'Run' (or Cmd+Enter)"
echo "      → Wait for success ✅"
echo ""
echo "   2. Open: database/auth-schema.sql"
echo "      → Repeat above steps"
echo ""
echo "   3. Open: database/visa-applications-schema.sql"
echo "      → Repeat above steps"
echo ""
echo "   4. Open: database/visa-pages-schema.sql"
echo "      → Repeat above steps"
echo ""
echo "   5. Open: database/sample-data.sql"
echo "      → Repeat above steps"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏱️  Total Time: 5 minutes"
echo "📊 Result: 29 database tables created"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 AFTER SETUP:"
echo ""
echo "   1. Create storage buckets:"
echo "      https://supabase.com/dashboard/project/esbzzprfghkcigvyuiw/storage/buckets"
echo "      - documents (Private)"
echo "      - tour-images (Public)"
echo ""
echo "   2. Run development server:"
echo "      npm run dev"
echo ""
echo "   3. Visit platform:"
echo "      http://localhost:3000"
echo ""
echo "🎉 YOUR PLATFORM WILL BE LIVE!"
echo ""

